title: Markdown Blog
description: >-
  Just a simple Blog
author: Joacim

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
